language: node_js
node_js:
  - "10"
branches:
  only:
    - master
cache:
  yarn: true
install:
  - yarn install
script:
  - yarn build
deploy:
  provider: pages
  local-dir: dist
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
